import "@/styles/globals.css";

import type { Metadata } from "next";

//fix to make MUI theme and Next.js working together with SSR components
//https://mui.com/material-ui/guides/next-js-app-router/
import ThemeRegistry from "./themeRegistry";

export const metadata: Metadata = {
  title: "Server / Client Components with MUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
